spring.application.name=NotesApp
frontend.url=${FRONTEND_URL}

# PostgreSQL Config
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# Hibernate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# CORS
spring.mvc.cors.allowed-origins=http://localhost:3000

# JWT Secret
jwt.secret=${JWT_SECRET}

server.port=${PORT:8080}