name: Login and Ping Sruthi's NotesApp

on:
  schedule:
    - cron: '*/13 * * * *'  # every 13 mins
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Login and Save JWT
        id: login
        run: |
          RESPONSE=$(curl -s -X POST https://sruthi-notesapp.netlify.app/api/auth/login \
            -H "Content-Type: application/json" \
            -d '{"username": "${{ secrets.LOGIN_USERNAME }}", "password": "${{ secrets.LOGIN_PASSWORD }}"}')

          echo "Raw response: $RESPONSE"
          
          TOKEN=$(echo "$RESPONSE" | jq -r '.token')
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Send Authenticated Request
        run: |
          curl -X GET https://your-backend-url.com/api/notes \
            -H "Authorization: Bearer ${{ steps.login.outputs.token }}" \
            || echo "Ping failed"
