name: Auto Login and Ping App

on:
  schedule:
    - cron: '*/13 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Login and Save JWT
        id: login
        run: |
          TOKEN=$(curl -s -X POST https://sruthi-notesapp.netlify.app/api/auth/login \
            -H "Content-Type: application/json" \
            -d '{"username": "${{ secrets.LOGIN_USERNAME }}", "password": "${{ secrets.LOGIN_PASSWORD }}"}' \
            | jq -r '.token')

          echo "Got token: $TOKEN"
          
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Send Authenticated Request
        run: |
          curl -X GET https://your-app.com/secured-endpoint \
            -H "Authorization: Bearer ${{ steps.login.outputs.token }}" \
            || echo "Request failed"
