name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/10 * * * *" # Every 13 minutes
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Make login request and extract token
        id: login
        run: |
          RESPONSE=$(curl -s -X POST https://notesapp-latest.onrender.com/api/auth/login \
            -H "Content-Type: application/json" \
            -d '{"username": "sru", "password": "sru}')
          
          echo "Raw response: $RESPONSE"
          
          TOKEN=$(echo "$RESPONSE" | jq -r '.token')
          echo "token=$TOKEN" >> $GITHUB_ENV

      - name: Ping protected notes endpoint
        run: |
          curl -X GET https://notesapp-latest.onrender.com/api/notes \
            -H "Authorization: Bearer $token"
